ongr-io/FilterManagerBundle

Filters/Widget/Choice/SingleTermChoice.php, composer.json
=> Elasticsearch version bump ~0.5.1

README.rst
=> Added badges and minor updates to README.rst

.travis.yml, composer.json
=> Updates .travis.yml

Pager/PagerService.php, Tests/Functional/Filters/Widget/Pager/PagerTest.php, Tests/Unit/Filters/Widget/Pager/PagerTest.php
=> Refactored PagerService constructor

DependencyInjection/Compiler/FilterPass.php, DependencyInjection/Configuration.php, DependencyInjection/ONGRFilterManagerExtension.php, ONGRFilterManagerBundle.php, Resources/doc/filter/choice.rst, Resources/doc/filter/custom_filter.rst, Resources/doc/filter/document_field.rst, Resources/doc/filter/match.rst, Resources/doc/filter/multi_choice.rst, Resources/doc/filter/pager.rst, Resources/doc/filter/sort.rst, Resources/doc/index.rst, Resources/doc/manager.rst, Resources/doc/setup.rst, Resources/doc/usage.rst, Tests/Functional/DependencyInjection/Compiler/FilterPassTest.php, Tests/Functional/Filters/Widget/Range/RangeTest.php, Tests/Unit/DependencyInjection/Compiler/FilterPassTest.php, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/app/config/config_test.yml, Tests/app/fixture/Acme/TestBundle/Filters/FooRange/FooRange.php, Tests/app/fixture/Acme/TestBundle/Resources/config/services.yml
=> [Feature] Custom filters using service tags

DependencyInjection/Configuration.php, DependencyInjection/ONGRFilterManagerExtension.php, Resources/config/services.yml, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/Unit/DependencyInjection/ONGRFilterManagerExtensionTest.php
=> Configuration not required

DependencyInjection/Configuration.php, DependencyInjection/ONGRFilterManagerExtension.php, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/app/config/config_test.yml
=> Repository is defined by ID

DependencyInjection/ONGRFilterManagerExtension.php, Tests/Unit/DependencyInjection/ONGRFilterManagerExtensionTest.php
=> unique filter names validation in configuration

.travis.yml, DependencyInjection/Configuration.php, Filters/Widget/Choice/SingleTermChoice.php, Pager/PagerService.php, composer.json
=> Updated bundle to use strict standard ~2.1.

.travis.yml, Filters/Widget/Choice/SingleTermChoice.php, Filters/Widget/Search/MatchSearch.php, Tests/Unit/Filters/Widget/Choice/SingleTermChoiceTest.php, composer.json
**merge after `ongr/elasticsearch-bundle 0.9` release**
=> Widgets update for elasticsearch bundle 0.9 release

DependencyInjection/Configuration.php, Filters/ViewData/Choice.php, Filters/Widget/Sort/Sort.php, Resources/doc/filter/sort.rst, Tests/Functional/Filters/Widget/Pager/PagerTest.php, Tests/Functional/Filters/Widget/Range/RangeTest.php, Tests/Functional/Filters/Widget/Sort/SortTest.php, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/app/fixture/Acme/TestBundle/Document/Product.php
=> added mode configuration to sorting

DependencyInjection/Configuration.php, DependencyInjection/Filter/ChoiceFilterFactory.php, DependencyInjection/Filter/MultiChoiceFilterFactory.php, Filters/Helper/SizeAwareTrait.php, Filters/Widget/Choice/SingleTermChoice.php, Tests/Functional/DependencyInjection/ServiceCreationTest.php, Tests/Functional/Filters/Widget/Choice/SingleTermChoiceTest.php, Tests/app/config/config_test.yml
=> Added size property for choice filters

Tests/Functional/Twig/PagerExtensionsTest.php, Tests/Unit/Twig/PagerExtensionTest.php, Tests/app/config/routing.yml
Closes https://github.com/ongr-io/FilterManagerBundle/issues/70
=> added functional and unit twig tests

Filters/Widget/AbstractSingleRequestValueFilter.php, Tests/Functional/Filters/Widget/Choice/MultiTermChoiceTest.php
This problem appears when one of choices is deactivated at multi choice filter.
=> Non ordered multi term choices should not throw elasticsearch exception.

Tests/app/config/routing.yml
pattern is deprecated and causing issues in travis
=> changed pattern to path

DependencyInjection/Configuration.php, DependencyInjection/Filter/RangeFilterFactory.php, Filters/Widget/Range/AbstractRange.php, Filters/Widget/Range/DateRange.php, Filters/Widget/Range/Range.php, Search/FiltersContainer.php, Tests/Functional/DependencyInjection/Compiler/FilterPassTest.php, Tests/Functional/Filters/Widget/Range/RangeTest.php, Tests/Unit/DependencyInjection/ConfigurationTest.php, Tests/app/config/config_test.yml
=> Inclusive range filter

Filters/Widget/Choice/MultiTermChoice.php, Tests/Functional/Filters/Widget/Choice/MultiTermChoiceTest.php
When the filter parameter is not an array an exception is raised.
* color=red vs color[0]=red
=> Accept non array values for multichoice filters

Resources/doc/filter/pager.rst, Twig/PagerExtension.php
#102 bugfix for ongr_paginate_path.
=> #102 bugfix for ongr_paginate_path.

DependencyInjection/ONGRFilterManagerExtension.php, Resources/config/services.yml, Search/FiltersManager.php, Search/FiltersManagerInterface.php
This adds an ability to extend filters manager
=> Implemented filters manager interface

Controller/ManagerController.php, Filters/FilterState.php, Filters/ViewData.php, Filters/ViewData/Choice.php, Filters/ViewData/ChoicesAwareViewData.php, Filters/ViewData/PagerAwareViewData.php, Filters/ViewData/RangeAwareViewData.php, Search/SearchResponse.php, SerializableInterface.php, Tests/Functional/Controller/ManagerControllerTest.php, Tests/Unit/Filters/ViewData/RangeAwareViewDataTest.php, Tests/Unit/Filters/ViewDataTest.php, Tests/app/config/routing.yml, Tests/app/fixture/Acme/TestBundle/Document/Product.php
New feature. In addition to rendered template we can now return "raw" JSON response. This allows to easily implement template rendering on user side.
=> Serializable search result (JSON response)

Filters/Widget/Range/DateRange.php
=> Simplify timestamp to DateTime object transformation

DependencyInjection/Compiler/FilterPass.php, Resources/doc/filter/custom_filter.rst, Tests/Unit/DependencyInjection/Compiler/FilterPassTest.php, Tests/app/config/config_test.yml, Tests/app/fixture/Acme/TestBundle/Resources/config/services.yml
=> Custom filters adding to manager in regular way [v0.5]

Tests/Unit/Twig/PagerExtensionTest.php, Twig/PagerExtension.php
=> Removed | deprecated method in Pager Extension

Controller/ManagerController.php, Tests/Functional/Controller/ManagerControllerTest.php
=> Adding 'pretty' parameter for json filters action.

Filters/Widget/Search/MatchSearch.php, Tests/Functional/Filters/Widget/Search/BoostedMatchTest.php
Documentation will come with separated PR.
Related to https://github.com/ongr-io/FilterManagerBundle/issues/139 .
=> Possibility to add boosting for fields in match filter.

Controller/ManagerController.php, Resources/doc/examples/custom_controller.md, Resources/doc/examples/using_document_field_filter.md, Search/FiltersManager.php, Search/FiltersManagerInterface.php, Test/AbstractFilterManagerResultsTest.php, Tests/Functional/Filters/Widget/Choice/MultiTermChoiceTest.php, Tests/Functional/Filters/Widget/Choice/SingleTermChoiceTest.php, Tests/Functional/Filters/Widget/Pager/PagerTest.php, Tests/Functional/Filters/Widget/Range/DateRangeTest.php, Tests/Functional/Filters/Widget/Range/RangeTest.php, Tests/Functional/Filters/Widget/Search/FuzzySearchTest.php, Tests/Functional/Filters/Widget/Search/MatchSearchTest.php, Tests/Functional/Filters/Widget/Search/VariantFilterTest.php, Tests/Functional/Filters/Widget/Sort/SortTest.php, Tests/Functional/Search/Response/UrlParametersTest.php, Tests/Functional/Search/ViewData/FilterStateTest.php, Tests/Functional/Search/ViewData/SingleTermChoice/SearchInfluenceTest.php, Tests/Unit/Controller/ManagerControllerTest.php, Tests/Unit/Search/FiltersManagerTest.php
=> Rename manager's execute() to handleRequest()

Resources/doc/examples/fields_boosting.md, Resources/doc/examples/search_example.md, Resources/doc/examples/using_document_field_filter.md, Test/AbstractFilterManagerResultsTest.php, Tests/Functional/Controller/ManagerControllerTest.php, Tests/Functional/DependencyInjection/ServiceCreationTest.php, Tests/Functional/Filter/Widget/Pager/PagerTest.php, Tests/Functional/Filter/Widget/Range/DateRangeTest.php, Tests/Functional/Filter/Widget/Range/RangeTest.php, Tests/Functional/Filter/Widget/Search/BoostedMatchTest.php, Tests/Functional/Filter/Widget/Search/FuzzySearchTest.php, Tests/Functional/Filter/Widget/Search/MatchSearchTest.php, Tests/Functional/Filter/Widget/Search/VariantFilterTest.php, Tests/Functional/Filter/Widget/Sort/SortTest.php, Tests/Functional/Search/ViewData/SingleTermChoice/SearchInfluenceTest.php, Tests/Functional/Twig/PagerExtensionsTest.php, Tests/app/fixture/Acme/TestBundle/Document/Product.php
Updated usages of document related stuff and updated manager usage in tests.
Don't need to hurry merging this.
=> Fixed compatibility with ElasticsearchBundle

Filter/Widget/Search/VariantFilter.php, README.md
Spotted these in Symfony profiler
=> Replace deprecated filters with queries

DependencyInjection/Configuration.php, DependencyInjection/Filter/MultiChoiceFilterFactory.php, Filter/Widget/Choice/MultiTermChoice.php, Tests/Functional/Filter/Widget/Choice/MultiTermChoiceTest.php, Tests/Unit/DependencyInjection/ConfigurationTest.php
=> Add AND and NOT_AND boolean operation into Multi Choice filter

.travis.yml
=> Run tests on both, old and new Elasticsearch versions

Resources/doc/filter/match.md
=> added info about multiple fields in the match filter description

DependencyInjection/Filter/DocumentValueFactory.php, DependencyInjection/Filter/FieldValueFactory.php, Filter/Widget/Search/FieldValue.php
Fixed wrong namespace path in DocumentField and FieldValue filter factories
=> Fixed wrong namespace paths

DependencyInjection/Configuration.php, DependencyInjection/ONGRFilterManagerExtension.php, ONGRFilterManagerBundle.php, Resources/doc/examples/search_example.md, Search/FilterContainer.php, Search/FilterManager.php
Cache search after processing filters
Relates to #30
=> Filter cache

DependencyInjection/ONGRFilterManagerExtension.php, Event/PreSearchEvent.php, Event/SearchResponseEvent.php, ONGRFilterManagerEvents.php, Resources/doc/examples/event_listener.md, Resources/doc/index.md, Search/FilterManager.php, Tests/Functional/Filter/Widget/Choice/MultiTermChoiceTest.php, Tests/Functional/Filter/Widget/Choice/SingleTermChoiceTest.php, Tests/Functional/Filter/Widget/Pager/PagerTest.php, Tests/Functional/Filter/Widget/Range/RangeTest.php, Tests/Functional/Filter/Widget/Search/BoostedMatchTest.php, Tests/Functional/Filter/Widget/Search/DocumentValueTest.php, Tests/Functional/Filter/Widget/Search/FuzzySearchTest.php, Tests/Functional/Filter/Widget/Search/MatchSearchTest.php, Tests/Functional/Filter/Widget/Sort/SortTest.php, Tests/Functional/Search/Response/UrlParametersTest.php, Tests/Functional/Search/Results/FieldValueTest.php, Tests/Functional/Search/Results/MatchSearchTest.php, Tests/Functional/Search/ViewData/FilterStateTest.php, Tests/Functional/Search/ViewData/SingleTermChoice/SearchInfluenceTest.php, Tests/Unit/Event/PreSearchEventTest.php, Tests/Unit/Event/SearchResponseEventTest.php, Tests/Unit/Search/FilterManagerTest.php
Introduced event dispatching.
Name | Argument
--- | ---
`ongr_filter_manager.pre_search` | **PreSearchEvent**
`ongr_filter_manager.search_response` | **SearchResponseEvent**
Closes #157
=> Event dispatching

Resources/doc/filter/match.md
=> included fuzziness and operator in the documentation of the match filter

DependencyInjection/Configuration.php, DependencyInjection/Filter/ChoiceFilterFactory.php, Filter/Widget/Choice/SingleTermChoice.php, Resources/doc/filter/choice.md, Resources/doc/filter/multi_choice.md, Tests/Functional/Filter/Widget/Choice/SingleTermChoiceTest.php, Tests/Unit/Filter/Widget/Choice/SingleTermChoiceTest.php, Tests/app/config/config_test.yml
Implemented the possibility of inclusion of choices with zero documents in the choice array of `ChoiceAwareViewData` in `ChoiceFilter` and `MultiChoiceFilter`.
=> Show zero choices

Filter/Widget/Search/MatchSearch.php, Tests/Functional/Filter/Widget/Search/MatchSearchTest.php, Tests/app/fixture/TestBundle/Document/Product.php, Tests/app/fixture/TestBundle/Document/Variant.php
My suggestion on the NestedSearch implementation. @tautrimas , could you take a look and check if this implementation would be something you would use? I think its not necessary to introduce a separate filter that does most of the same things that the normal Match filter does, don't you?
closes #172
=> Added nested implementation in match search

Filter/Widget/Search/MatchSearch.php, Tests/Functional/Filter/Widget/Search/MatchSearchTest.php
Changed nested separator in match filter
=> Changed nested separator

Filter/Widget/Search/DocumentValue.php, Tests/Functional/Filter/Widget/Search/DocumentValueTest.php, Tests/app/config/filters/search.yml
=> Fix for property if it is private in the document

Filter/Widget/Range/AbstractRange.php, Filter/Widget/Range/DateRange.php, Filter/Widget/Range/Range.php, Tests/Functional/Filter/Widget/Range/DateRangeTest.php, Tests/Functional/Filter/Widget/Range/RangeTest.php, Tests/app/config/filters/range.yml
Made range filters use related search instance for their bounds formation
=> Range bounds formation fix

Filter/Widget/Choice/SingleTermChoice.php, Tests/Functional/Filter/Widget/Choice/SingleTermChoiceTest.php, Tests/app/config/config_test.yml
=> implemented exception when array given to choice

Event/PreProcessSearchEvent.php, ONGRFilterManagerEvents.php, Search/FilterManager.php, Tests/Unit/Event/PreProcessSearchEventTest.php
=> Pre Process search event

DependencyInjection/Compiler/FilterPass.php, Resources/doc/Configuration.md, Resources/doc/Relations.md, Tests/Functional/DependencyInjection/Compiler/FilterPassTest.php, Tests/Unit/DependencyInjection/Compiler/FilterPassTest.php, Tests/app/config/config_test.yml
Reintroduced filter relations and wrote the documentation for them, since the section was missing
=> Reintroduced Filter relations

Twig/PagerExtension.php
=> fix PagerExtension is dependent to deprecated function Twig_Function

composer.json
https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/2.0.0
=> JMS Serializer update to 2.0

Tests/Unit/Controller/ManagerControllerTest.php
Changes for issue https://github.com/ongr-io/FilterManagerBundle/issues/248
=> Fix tests in 2.1 branch

Resources/doc/filter/sort.md
I try use sort filter and seen error in example.
=> Forgot `options` field in sort example
